@startuml вариант 2, Комплекс управления животноводством

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
Person(оператор, "Оператор", "Использует систему")
Person(животновод, "Животновод", "Использует систему")

System_Boundary(платформа, "АгроПром Х - Цифровая платформа") {

    System_Boundary(центральный_сервер, "Комплекс управления животноводством") {
        System(управление_животноводством, "Система управления животноводством в целом", "Управление и агрегация данных с ферм")
        System(управление_фермой, "Система управления отдельной фермой")
    }

    Container(kafka, "Брокер сообщений", "Apache Kafka", "Шина данных")

}

' === Взаимосвязи ===
Rel(животновод, управление_животноводством, "Использует")
Rel(оператор, управление_фермой, "Использует")


Rel(управление_фермой, управление_животноводством, "Cинхронизация данных", "REST")
Rel(управление_животноводством, kafka, "Публикует данные", "Kafka Protocol")


@enduml